//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_LOGICA_NEGOCIO.WS_Altura_Planta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices/", ConfigurationName="WS_Altura_Planta.CapturarAltura")]
    public interface CapturarAltura {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://WebServices/).
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/CapturarAltura/AlturaValorClienteRequest", ReplyAction="http://WebServices/CapturarAltura/AlturaValorClienteResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse AlturaValorCliente(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/CapturarAltura/AlturaValorClienteRequest", ReplyAction="http://WebServices/CapturarAltura/AlturaValorClienteResponse")]
        System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse> AlturaValorClienteAsync(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/CapturarAltura/CapturarAlturaValorRequest", ReplyAction="http://WebServices/CapturarAltura/CapturarAlturaValorResponse")]
        CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse CapturarAlturaValor(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/CapturarAltura/CapturarAlturaValorRequest", ReplyAction="http://WebServices/CapturarAltura/CapturarAlturaValorResponse")]
        System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse> CapturarAlturaValorAsync(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlturaValorCliente", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class AlturaValorClienteRequest {
        
        public AlturaValorClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlturaValorClienteResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class AlturaValorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public AlturaValorClienteResponse() {
        }
        
        public AlturaValorClienteResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturarAlturaValorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturarAlturaValor", Namespace="http://WebServices/", Order=0)]
        public CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequestBody Body;
        
        public CapturarAlturaValorRequest() {
        }
        
        public CapturarAlturaValorRequest(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CapturarAlturaValorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AlturaInicial;
        
        public CapturarAlturaValorRequestBody() {
        }
        
        public CapturarAlturaValorRequestBody(int AlturaInicial) {
            this.AlturaInicial = AlturaInicial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturarAlturaValorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturarAlturaValorResponse", Namespace="http://WebServices/", Order=0)]
        public CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponseBody Body;
        
        public CapturarAlturaValorResponse() {
        }
        
        public CapturarAlturaValorResponse(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CapturarAlturaValorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CapturarAlturaValorResponseBody() {
        }
        
        public CapturarAlturaValorResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CapturarAlturaChannel : CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CapturarAlturaClient : System.ServiceModel.ClientBase<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura>, CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura {
        
        public CapturarAlturaClient() {
        }
        
        public CapturarAlturaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CapturarAlturaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapturarAlturaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapturarAlturaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura.AlturaValorCliente(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest request) {
            return base.Channel.AlturaValorCliente(request);
        }
        
        public long AlturaValorCliente() {
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest inValue = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest();
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse retVal = ((CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura)(this)).AlturaValorCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse> CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura.AlturaValorClienteAsync(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest request) {
            return base.Channel.AlturaValorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteResponse> AlturaValorClienteAsync() {
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest inValue = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.AlturaValorClienteRequest();
            return ((CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura)(this)).AlturaValorClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura.CapturarAlturaValor(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest request) {
            return base.Channel.CapturarAlturaValor(request);
        }
        
        public string CapturarAlturaValor(int AlturaInicial) {
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest inValue = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest();
            inValue.Body = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequestBody();
            inValue.Body.AlturaInicial = AlturaInicial;
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse retVal = ((CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura)(this)).CapturarAlturaValor(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse> CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura.CapturarAlturaValorAsync(CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest request) {
            return base.Channel.CapturarAlturaValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorResponse> CapturarAlturaValorAsync(int AlturaInicial) {
            CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest inValue = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequest();
            inValue.Body = new CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAlturaValorRequestBody();
            inValue.Body.AlturaInicial = AlturaInicial;
            return ((CAPA_LOGICA_NEGOCIO.WS_Altura_Planta.CapturarAltura)(this)).CapturarAlturaValorAsync(inValue);
        }
    }
}
